### PR TITLE
Improved support for extensions

### PR DESCRIPTION
**Pull request by cdrake**
Added support for multiple extensions and serializing extensions. I used this [document as guidance](https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/extension.html).

### CODE REVIEW

**Comment by neurolabusc** [comment]
@martinezmj and @rii-mango is there any way we could @hanayik become a maintainer for NIFTI-Reader-JS, GIFTI-Reader-JS, papaya and Daikon? He can manage pull requests and updating the npm releases in a timely manner. The community has generated PRs that fix bugs, improve performance and extend these crucial libraries. I note that a Daikon PR remains unreviewed when it was submitted on Nov 11, 2019. 

Our team heavily leverages these libraries for our tools. In general, the quality of code in these libraries is outstanding. However, support for complicated targets like DICOM I a moving target. The commit records show the original developer have moved on to other projects. Our team can be prudent custodians for this software. We much prefer having a unified, curated set of libraries rather than creating the confusion associated with forking this project.

**Comment by martinezmj** [comment]
Hi @neurolabusc , @martinezmj (aka @rii-mango) here -- sorry for the very late reply.  If it's not too late, I want to help.

I no longer work at the RII (the imaging institute at UT Health) where these projects were built.  I tried, before I left, to get someone to take them over, but it didn't work out.  I tried to maintain them on a part-time/weekend basis for a few years after that, but eventually had too many other things going on to keep up with them.

I'll reach out to my contacts at the RII and see what can be worked out.  At least having someone to keep on top of PRs would be good.  I'd love to see the projects carry on.

**Comment by neurolabusc** [comment]
Great. Happy to have a zoom meeting or email exchange with any of the original developers if it would help.

**Comment by neurolabusc** [comment]
@martinezmj @rii-mango would be happy to make progress on this. Optimizations like using `fflate` instead of `pako` will double performance for compressed data that will aid Papaya, NiiVue and any other tools that use these libraries. Our tuning of GIfTI, NIfTI and DICOM will help handle edge cases. You created a fantastic foundation, and I strongly prefer a single unified code base versus forking these projects.

**Pull request merged**
